<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The WildFly Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:wildfly:tls-secrets:1.0"
            xmlns="urn:wildfly:tls-secrets:1.0"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.0">

    <xsd:element name="subsystem" type="subsystemType"/>

    <xsd:complexType name="subsystemType">
        <xsd:sequence>
            <xsd:element name="key-store" type="keyStoreType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="keyStoreType">
        <xsd:attribute name="name" type="nonEmptyString" use="required"/>
        <xsd:attribute name="path" type="nonEmptyString" use="required"/>
        <xsd:attribute name="alias" type="nonEmptyString" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="nonEmptyString">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>
